#version 450
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_atomic_float : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#define TS 256
#define vec 4
#define d_model 4096

layout(local_size_x = TS, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Dimensions {
    uint M;
    uint N;
    uint K;
} dims;

const float EPSILON = 1e-5;

layout(set = 0, binding = 0) buffer DataBuffer { vec4 x[]; };
layout(set = 0, binding = 1) readonly buffer GammaBuffer { vec4 gamma[]; };
layout(set = 0, binding = 2) readonly buffer weightBuffer { vec4 w[]; };
layout(set = 0, binding = 3) writeonly buffer outBuffer { float y[]; };


shared float shared_sum;
shared vec4 cache[d_model/vec];

void main() {
    uint col = gl_LocalInvocationID.x;
    uint globalCol = gl_WorkGroupID.x*TS + col;
    if (globalCol >= dims.N) return;
    
    float sum_sq = 0.0;

    for (uint t = 0; t < dims.K; t+=TS) {
        uint idx = t + col;
        vec4 val = x[idx];
        cache[idx] = val * gamma[idx];
        sum_sq += dot(val, val);
    }

    sum_sq = subgroupAdd(sum_sq);

    if (subgroupElect()) {
        if (gl_SubgroupID == 0) {
            shared_sum = 0.0;
        }
        barrier();
        memoryBarrierBuffer();
        atomicAdd(shared_sum, sum_sq);
    }

    barrier();
    float rms = sqrt((shared_sum / float(d_model)) + EPSILON);
    float inv_rms = 1.0 / rms;
    
    float acc = 0.0;
    uint baseRow = 0;
    #pragma unroll
    for (uint k=0;k<dims.K/vec; k++) {
        acc += dot(cache[k] * inv_rms, w[baseRow + globalCol]);
        baseRow += dims.N;
    }

    y[globalCol] = acc;
}