#version 450
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_atomic_float : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#define TS 256
#define vec 4
#define d_model 4096
#define K_OFF 2048
#define V_OFF 4096
#define G_OFF 8192
#define A_OFF 12288
#define B_OFF 12320

layout(local_size_x = TS, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Dimensions {
    uint M;
    uint N;
    uint K;
    uint V;
} param;

const float EPSILON = 1e-5;

layout(set = 0, binding = 0) readonly restrict buffer TokenBuffer { uint tokenIds[]; };
layout(set = 0, binding = 1) readonly restrict buffer EmbedBuffer { uvec4 lm[]; };
layout(set = 0, binding = 2) readonly buffer GammaBuffer { vec4 gamma[]; };
layout(set = 0, binding = 3) readonly buffer weightBuffer { uvec4 w[]; };
layout(set = 0, binding = 4) buffer qOutBuffer { float qOut[]; };
layout(set = 0, binding = 5) buffer kOutBuffer { float kOut[]; };
layout(set = 0, binding = 6) buffer vOutBuffer { float vOut[]; };
layout(set = 0, binding = 7) buffer gOutBuffer { float gOut[]; };
layout(set = 0, binding = 8) buffer aOutBuffer { float aOut[]; };
layout(set = 0, binding = 9) buffer bOutBuffer { float bOut[]; };
layout(set = 0, binding = 10) buffer embOutBuffer { float embOut[]; };

shared float shared_sum;
shared vec4 cache[d_model/vec];
shared float sub_sums[TS / 64];

void main() {
    uint col = gl_LocalInvocationID.x;
    uint globalCol = gl_WorkGroupID.x*TS + col;
    uint tok = tokenIds[0];

    float sum_sq = 0.0;

    for (uint t = 0; t < param.K/vec; t+=TS) {
        uint idx = t + col;
        uvec4 raw = lm[(idx / 2u) * param.V + tok];
        vec4 val = ((idx & 1u) == 0u)
            ? vec4(unpackHalf2x16(raw.x), unpackHalf2x16(raw.y))
            : vec4(unpackHalf2x16(raw.z), unpackHalf2x16(raw.w));
        cache[idx] = val * gamma[idx];
        embOut[idx * 4u + 0u] = val.x;
        embOut[idx * 4u + 1u] = val.y;
        embOut[idx * 4u + 2u] = val.z;
        embOut[idx * 4u + 3u] = val.w;
        sum_sq += dot(val, val);
    }

    sum_sq = subgroupAdd(sum_sq);
    if (subgroupElect()) {
        sub_sums[gl_SubgroupID] = sum_sq;
    }
    barrier();

    if (gl_LocalInvocationID.x == 0) {
        float final_sum = 0.0;
        uint active_subgroups = (TS + gl_SubgroupSize - 1) / gl_SubgroupSize;
        for (uint i = 0; i < active_subgroups; i++) {
            final_sum += sub_sums[i];
        }
        shared_sum = final_sum;
    }
    barrier();
    float rms = sqrt((shared_sum / float(d_model)) + EPSILON);
    float inv_rms = 1.0 / rms;

    if (globalCol >= param.N) return;

    float acc = 0.0;
    uint baseRow = 0;
    #pragma unroll
    for (uint k=0;k<param.K/vec; k+=2) {
        uvec4 rawInput = w[baseRow + globalCol];
        vec4 outVectorA = vec4(unpackHalf2x16(rawInput.x), unpackHalf2x16(rawInput.y));
        vec4 outVectorB = vec4(unpackHalf2x16(rawInput.z), unpackHalf2x16(rawInput.w));
        acc += dot(cache[k] * inv_rms, outVectorA);
        acc += dot(cache[k+1] * inv_rms, outVectorB);
        baseRow += param.N;
    }

    if (globalCol < K_OFF) {
        qOut[globalCol] = acc;
    } else if (globalCol < V_OFF) {
        kOut[globalCol - K_OFF] = acc;
    } else if (globalCol < G_OFF) {
        vOut[globalCol - V_OFF] = acc;
    } else if (globalCol < A_OFF) {
        gOut[globalCol - G_OFF] = acc;
    } else if (globalCol < B_OFF) {
        aOut[globalCol - A_OFF] = acc;
    } else {
        bOut[globalCol - B_OFF] = acc;
    }
}