#version 450
#define TS 256
#define vec 4
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = TS, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Dimensions {
    uint M;
    uint N;
    uint K;
} dims;

layout(set = 0, binding = 0) readonly restrict buffer PartialBuffer { vec4 PgPu[]; };
layout(set = 0, binding = 1) readonly restrict buffer MatrixB { uvec4 B[]; };
layout(set = 0, binding = 2) writeonly restrict buffer PartialOutBuffer { float P[]; };
layout(set = 0, binding = 3) readonly restrict buffer MatrixD { vec4 scale[]; };
layout(set = 0, binding = 4) readonly restrict buffer MatrixE { vec4 zeroPoint[]; };

shared vec4 aSub[2][TS];
shared vec4 scaleSub[2][TS];
shared vec4 zeroSub[2][TS];

const uvec4 lowShifts  = uvec4(0, 4, 8, 12);
const uvec4 highShifts = uvec4(16, 20, 24, 28);

vec4 unpackInt4x4(uint packedComponent, uvec4 shiftOffsets) {
    return vec4(uvec4(packedComponent) >> shiftOffsets & uvec4(0xF));
}

vec4 loadAct(uint idx) {
    vec4 g = vec4(0.0);
    vec4 u = vec4(0.0);
    for (uint z = 0; z < 4u; z++) {
        g += PgPu[z * dims.K / vec + idx];
        u += PgPu[(4u + z) * dims.K / vec + idx];
    }
    return (g / (vec4(1.0) + exp2(-g * 1.44269504))) * u;
}

void main() {
    uint col = gl_LocalInvocationID.x;
    uint chunk = gl_WorkGroupID.y;
    uint globalCol = gl_WorkGroupID.x*TS + col;
    if (globalCol >= dims.N) return;
    uint scaleIdx = gl_WorkGroupID.x * dims.K / vec + col;

    float acc = 0.0;
    uint numTiles = (dims.K + TS - 1) / TS / vec;
    if (globalCol < dims.N && chunk < numTiles) {
        aSub[0][col] = loadAct(chunk*TS + col);
        scaleSub[0][col] = scale[chunk*TS + scaleIdx];
        zeroSub[0][col] = zeroPoint[chunk*TS + scaleIdx];
    }

    barrier();
    uint it = 0;
    for (uint t = chunk; t < numTiles; t += 4u) {
        uint cur = it & 1, nxt = (it+1) & 1;
        uint nextTile = t + 4u;
        if (nextTile < numTiles) {
            aSub[nxt][col] = loadAct(nextTile*TS + col);
            scaleSub[nxt][col] = scale[nextTile*TS + scaleIdx];
            zeroSub[nxt][col] = zeroPoint[nextTile*TS + scaleIdx];
        }

        uint baseRow = t * (TS / 8) * dims.N;
        #pragma unroll
        for (uint k=0;k<TS; k+=8) {
            uvec4 rawInput = B[baseRow + globalCol];
            vec4 w0 = unpackInt4x4(rawInput.x, lowShifts) * scaleSub[cur][k] - zeroSub[cur][k];
            vec4 w1 = unpackInt4x4(rawInput.x, highShifts) * scaleSub[cur][k+1] - zeroSub[cur][k+1];
            vec4 w2 = unpackInt4x4(rawInput.y, lowShifts) * scaleSub[cur][k+2] - zeroSub[cur][k+2];
            vec4 w3 = unpackInt4x4(rawInput.y, highShifts) * scaleSub[cur][k+3] - zeroSub[cur][k+3];
            vec4 w4 = unpackInt4x4(rawInput.z, lowShifts) * scaleSub[cur][k+4] - zeroSub[cur][k+4];
            vec4 w5 = unpackInt4x4(rawInput.z, highShifts) * scaleSub[cur][k+5] - zeroSub[cur][k+5];
            vec4 w6 = unpackInt4x4(rawInput.w, lowShifts) * scaleSub[cur][k+6] - zeroSub[cur][k+6];
            vec4 w7 = unpackInt4x4(rawInput.w, highShifts) * scaleSub[cur][k+7] - zeroSub[cur][k+7];

            acc += dot(aSub[cur][k], w0);
            acc += dot(aSub[cur][k+1], w1);
            acc += dot(aSub[cur][k+2], w2);
            acc += dot(aSub[cur][k+3], w3);
            acc += dot(aSub[cur][k+4], w4);
            acc += dot(aSub[cur][k+5], w5);
            acc += dot(aSub[cur][k+6], w6);
            acc += dot(aSub[cur][k+7], w7);
            baseRow += dims.N;
        }

        barrier();
        it++;
    }
    P[chunk * dims.N + globalCol] = acc;
}
