#version 450
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#define TS 256
#define vec 4
#define d_model 4096

layout(local_size_x = TS, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Dimensions {
    uint M;
    uint N;
    uint K;
    uint off;
} dims;

const float EPSILON = 1e-6;

layout(set = 0, binding = 0) readonly restrict buffer MatrixA { vec4 x[]; };
layout(set = 0, binding = 1) readonly restrict buffer MatrixB { vec4 gamma[]; };
layout(set = 0, binding = 2) readonly restrict buffer MatrixC { uvec4 gate[]; };
layout(set = 0, binding = 3) readonly restrict buffer MatrixD { uvec4 up[]; };
layout(set = 0, binding = 4) writeonly restrict buffer PartialBuffer { float PgPu[]; };
layout(set = 0, binding = 5) readonly restrict buffer MatrixF { vec4 scaleGate[]; };
layout(set = 0, binding = 6) readonly restrict buffer MatrixG { vec4 zeroPointGate[]; };
layout(set = 0, binding = 7) readonly restrict buffer MatrixH { vec4 scaleUp[]; };
layout(set = 0, binding = 8) readonly restrict buffer MatrixI { vec4 zeroPointUp[]; };

shared float shared_sum;
shared vec4 xsCache[2][TS];
shared float sub_sums[TS / 64];

vec4 unpackInt4x4(uint packedComponent) {
    return vec4(uvec4(bitfieldExtract(packedComponent, 0, 4),
                      bitfieldExtract(packedComponent, 4, 4),
                      bitfieldExtract(packedComponent, 8, 4),
                      bitfieldExtract(packedComponent, 12, 4)));
}

vec4 unpackInt4x4High(uint packedComponent) {
    return vec4(uvec4(bitfieldExtract(packedComponent, 16, 4),
                      bitfieldExtract(packedComponent, 20, 4),
                      bitfieldExtract(packedComponent, 24, 4),
                      bitfieldExtract(packedComponent, 28, 4)));
}

void main() {
    uint col = gl_LocalInvocationID.x;
    uint chunk = gl_WorkGroupID.y;
    uint globalCol = gl_WorkGroupID.x*TS + col;
    uint upHalf = uint(globalCol >= dims.off);
    if (upHalf == 1u) globalCol -= dims.off;
    uint blockIdx = (gl_WorkGroupID.x - upHalf * (dims.off / TS)) * dims.K / vec + col;

    float sum_sq = 0.0;
    uint numTiles = (dims.K + TS - 1) / TS / vec;
    for (uint t = 0; t < dims.K/vec; t+=TS) {
        vec4 val = x[t + col];
        sum_sq += dot(val, val);
    }

    sum_sq = subgroupAdd(sum_sq);
    if (subgroupElect()) {
        sub_sums[gl_SubgroupID] = sum_sq;
    }
    barrier();

    if (gl_LocalInvocationID.x == 0) {
        float final_sum = 0.0;
        uint active_subgroups = (TS + gl_SubgroupSize - 1) / gl_SubgroupSize;
        for (uint i = 0; i < active_subgroups; i++) {
            final_sum += sub_sums[i];
        }
        shared_sum = final_sum;
    }
    barrier();
    float inv_rms = 1.0 / sqrt((shared_sum / float(d_model)) + EPSILON);

    float ztot = 0.0;
    if (chunk < numTiles) {
        vec4 sc;
        vec4 zc;
        if (upHalf == 1u) {
            sc = scaleUp[chunk*TS + blockIdx];
            zc = zeroPointUp[chunk*TS + blockIdx];
        } else {
            sc = scaleGate[chunk*TS + blockIdx];
            zc = zeroPointGate[chunk*TS + blockIdx];
        }
        vec4 xa = x[chunk*TS + col] * gamma[chunk*TS + col] * inv_rms;
        xsCache[0][col] = xa * sc;
        float zp = subgroupAdd(dot(xa * zc, vec4(1.0)));
        if (subgroupElect()) {
            sub_sums[gl_SubgroupID] = zp;
        }
    }

    barrier();
    if (chunk < numTiles) {
        ztot += sub_sums[0] + sub_sums[1] + sub_sums[2] + sub_sums[3];
    }

    uint blockCount = 0;
    float result = 0.0;

    for (uint t = chunk; t < numTiles; t += 4u) {
        uint cur = blockCount & 1, nxt = (blockCount+1) & 1;
        uint nextTile = t + 4u;
        if (nextTile < numTiles) {
            vec4 sc;
            vec4 zc;
            if (upHalf == 1u) {
                sc = scaleUp[nextTile*TS + blockIdx];
                zc = zeroPointUp[nextTile*TS + blockIdx];
            } else {
                sc = scaleGate[nextTile*TS + blockIdx];
                zc = zeroPointGate[nextTile*TS + blockIdx];
            }
            vec4 xa = x[nextTile*TS + col] * gamma[nextTile*TS + col] * inv_rms;
            xsCache[nxt][col] = xa * sc;
            float zp = subgroupAdd(dot(xa * zc, vec4(1.0)));
            if (subgroupElect()) {
                sub_sums[gl_SubgroupID] = zp;
            }
        }
        barrier();
        if (nextTile < numTiles) {
            ztot += sub_sums[0] + sub_sums[1] + sub_sums[2] + sub_sums[3];
        }
        blockCount++;

        uint baseRow = t * (TS / 8) * dims.N;
        #pragma unroll
        for (uint k=0;k<TS; k+=16) {
            uvec4 ra;
            uvec4 rb;
            if (upHalf == 1u) {
                ra = up[baseRow + globalCol];
                rb = up[baseRow + dims.N + globalCol];
            } else {
                ra = gate[baseRow + globalCol];
                rb = gate[baseRow + dims.N + globalCol];
            }
            result += dot(xsCache[cur][k], unpackInt4x4(ra.x));
            result += dot(xsCache[cur][k+1], unpackInt4x4High(ra.x));
            result += dot(xsCache[cur][k+2], unpackInt4x4(ra.y));
            result += dot(xsCache[cur][k+3], unpackInt4x4High(ra.y));
            result += dot(xsCache[cur][k+4], unpackInt4x4(ra.z));
            result += dot(xsCache[cur][k+5], unpackInt4x4High(ra.z));
            result += dot(xsCache[cur][k+6], unpackInt4x4(ra.w));
            result += dot(xsCache[cur][k+7], unpackInt4x4High(ra.w));
            result += dot(xsCache[cur][k+8], unpackInt4x4(rb.x));
            result += dot(xsCache[cur][k+9], unpackInt4x4High(rb.x));
            result += dot(xsCache[cur][k+10], unpackInt4x4(rb.y));
            result += dot(xsCache[cur][k+11], unpackInt4x4High(rb.y));
            result += dot(xsCache[cur][k+12], unpackInt4x4(rb.z));
            result += dot(xsCache[cur][k+13], unpackInt4x4High(rb.z));
            result += dot(xsCache[cur][k+14], unpackInt4x4(rb.w));
            result += dot(xsCache[cur][k+15], unpackInt4x4High(rb.w));

            baseRow += 2 * dims.N;
        }

        barrier();
    }

    PgPu[(upHalf * 4u + chunk) * dims.N + globalCol] = result - ztot;
}
