#version 450
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_atomic_float : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#define TS 256
#define vec 4
#define d_model 4096
#define SPLIT 4

layout(local_size_x = TS, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Dimensions {
    uint M;
    uint N;
    uint K;
} param;

const float EPSILON = 1e-5;

layout(set = 0, binding = 0) buffer DataBuffer { vec4 x[]; };
layout(set = 0, binding = 1) readonly buffer GammaBuffer { vec4 gamma[]; };
layout(set = 0, binding = 2) readonly buffer weightBuffer { uvec4 w[]; };
layout(set = 0, binding = 3) readonly restrict buffer MatrixD { vec4 scale[]; };
layout(set = 0, binding = 4) readonly restrict buffer MatrixE { vec4 zeroPoint[]; };
layout(set = 0, binding = 5) writeonly buffer PartialBuffer { float P[]; };

shared float shared_sum;
shared vec4 cache[d_model/vec];
shared vec4 scaleCache[d_model/vec];
shared float sub_sums[TS / 64];

vec4 unpackInt4x4(uint packedComponent) {
    return vec4(uvec4(bitfieldExtract(packedComponent, 0, 4),
                      bitfieldExtract(packedComponent, 4, 4),
                      bitfieldExtract(packedComponent, 8, 4),
                      bitfieldExtract(packedComponent, 12, 4)));
}

vec4 unpackInt4x4High(uint packedComponent) {
    return vec4(uvec4(bitfieldExtract(packedComponent, 16, 4),
                      bitfieldExtract(packedComponent, 20, 4),
                      bitfieldExtract(packedComponent, 24, 4),
                      bitfieldExtract(packedComponent, 28, 4)));
}

void main() {
    uint col = gl_LocalInvocationID.x;
    uint chunk = gl_WorkGroupID.y;
    uint globalCol = gl_WorkGroupID.x*TS + col;
    uint safeCol = min(globalCol, param.N - 1u);

    uint scaleIdx = gl_WorkGroupID.x * param.K / vec;
    float sum_sq = 0.0;

    for (uint t = 0; t < param.K/vec; t+=TS) {
        uint idx = t + col;
        vec4 val = x[idx];
        cache[idx] = val * gamma[idx];
        scaleCache[idx] = scale[idx + scaleIdx];
        sum_sq += dot(val, val);
    }

    sum_sq = subgroupAdd(sum_sq);
    if (subgroupElect()) {
        sub_sums[gl_SubgroupID] = sum_sq;
    }
    barrier();

    if (gl_LocalInvocationID.x == 0) {
        float final_sum = 0.0;
        uint active_subgroups = (TS + gl_SubgroupSize - 1) / gl_SubgroupSize;
        for (uint i = 0; i < active_subgroups; i++) {
            final_sum += sub_sums[i];
        }
        shared_sum = final_sum;
    }
    barrier();
    float inv_rms = 1.0 / sqrt((shared_sum / float(d_model)) + EPSILON);

    uint kvStart = chunk * (param.K / vec / SPLIT);
    uint kvEnd = kvStart + param.K / vec / SPLIT;
    float acc = 0.0;
    uint baseRow = (kvStart / 8) * param.N;

    scaleCache[kvStart + col] *= cache[kvStart + col] * inv_rms;
    float zp = subgroupAdd(dot(cache[kvStart + col] * inv_rms * zeroPoint[(kvStart + col) + scaleIdx], vec4(1.0)));
    if (subgroupElect()) {
        sub_sums[gl_SubgroupID] = zp;
    }
    barrier();
    float ztot = sub_sums[0] + sub_sums[1] + sub_sums[2] + sub_sums[3];

    #pragma unroll
    for (uint k=kvStart;k<kvEnd; k+=8) {
        uvec4 rawInput = w[baseRow + safeCol];
        acc += dot(scaleCache[k], unpackInt4x4(rawInput.x));
        acc += dot(scaleCache[k+1], unpackInt4x4High(rawInput.x));
        acc += dot(scaleCache[k+2], unpackInt4x4(rawInput.y));
        acc += dot(scaleCache[k+3], unpackInt4x4High(rawInput.y));
        acc += dot(scaleCache[k+4], unpackInt4x4(rawInput.z));
        acc += dot(scaleCache[k+5], unpackInt4x4High(rawInput.z));
        acc += dot(scaleCache[k+6], unpackInt4x4(rawInput.w));
        acc += dot(scaleCache[k+7], unpackInt4x4High(rawInput.w));
        baseRow += param.N;
    }

    if (globalCol < param.N) {
        P[chunk * param.N + globalCol] = acc - ztot;
    }
}
