#version 450
#define TS 256
#define vec 4
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = TS, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Dimensions {
    uint M;
    uint N;
    uint K;
} dims;

layout(set = 0, binding = 0) readonly restrict buffer PartialBuffer { vec4 PgPu[]; };
layout(set = 0, binding = 1) readonly restrict buffer MatrixB { uvec4 B[]; };
layout(set = 0, binding = 2) writeonly restrict buffer PartialOutBuffer { float P[]; };
layout(set = 0, binding = 3) readonly restrict buffer MatrixD { vec4 scale[]; };
layout(set = 0, binding = 4) readonly restrict buffer MatrixE { vec4 zeroPoint[]; };

shared vec4 asSub[2][TS];
shared float sub_sums[(TS + 31) / 32];

vec4 unpackUint8x4(uint packedData) {
    uvec4 bytes = (uvec4(packedData) >> uvec4(0, 8, 16, 24)) & uvec4(0xFF);
    return vec4(bytes);
}

vec4 loadAct(uint idx) {
    vec4 g = vec4(0.0);
    vec4 u = vec4(0.0);
    for (uint z = 0; z < 4u; z++) {
        g += PgPu[z * dims.K / vec + idx];
        u += PgPu[(4u + z) * dims.K / vec + idx];
    }
    return (g / (vec4(1.0) + exp2(-g * 1.44269504))) * u;
}

void main() {
    uint col = gl_LocalInvocationID.x;
    uint chunk = gl_WorkGroupID.y;
    uint globalCol = gl_WorkGroupID.x*TS + col;
    if (globalCol >= dims.N) return;
    uint scaleIdx = gl_WorkGroupID.x * dims.K / vec + col;

    float ztot = 0.0;
    float acc = 0.0;
    uint numTiles = (dims.K + TS - 1) / TS / vec;
    if (chunk < numTiles) {
        vec4 act = loadAct(chunk*TS + col);
        asSub[0][col] = act * scale[chunk*TS + scaleIdx];
        float zp = subgroupAdd(dot(act * zeroPoint[chunk*TS + scaleIdx], vec4(1.0)));
        if (subgroupElect()) {
            sub_sums[gl_SubgroupID] = zp;
        }
    }

    barrier();
    if (chunk < numTiles) {
        for (uint i = 0; i < gl_NumSubgroups; i++) ztot += sub_sums[i];
    }

    uint it = 0;
    for (uint t = chunk; t < numTiles; t += 4u) {
        uint cur = it & 1, nxt = (it+1) & 1;
        uint nextTile = t + 4u;
        if (nextTile < numTiles) {
            vec4 act = loadAct(nextTile*TS + col);
            asSub[nxt][col] = act * scale[nextTile*TS + scaleIdx];
            float zp = subgroupAdd(dot(act * zeroPoint[nextTile*TS + scaleIdx], vec4(1.0)));
            if (subgroupElect()) {
                sub_sums[gl_SubgroupID] = zp;
            }
        }
        barrier();
        if (nextTile < numTiles) {
            for (uint i = 0; i < gl_NumSubgroups; i++) ztot += sub_sums[i];
        }

        uint baseRow = t * (TS / 4) * dims.N;
        #pragma unroll
        for (uint k=0;k<TS; k+=4) {
            uvec4 rawInput = B[baseRow + globalCol];
            acc += dot(asSub[cur][k], unpackUint8x4(rawInput.x));
            acc += dot(asSub[cur][k+1], unpackUint8x4(rawInput.y));
            acc += dot(asSub[cur][k+2], unpackUint8x4(rawInput.z));
            acc += dot(asSub[cur][k+3], unpackUint8x4(rawInput.w));
            baseRow += dims.N;
        }

        barrier();
        it++;
    }
    P[chunk * dims.N + globalCol] = acc - ztot;
}
