#version 450
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_atomic_float : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#define TS 256
#define vec 4
#define d_model 4096

layout(local_size_x = TS, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Dimensions {
    uint M;
    uint N;
    uint K;
} param;

const float EPSILON = 1e-5;

layout(set = 0, binding = 0) buffer DataBuffer { vec4 x[]; };
layout(set = 0, binding = 1) readonly buffer GammaBuffer { vec4 gamma[]; };
layout(set = 0, binding = 2) readonly buffer weightBuffer { uvec4 w[]; };
layout(set = 0, binding = 3) readonly restrict buffer MatrixD { vec4 scale[]; };
layout(set = 0, binding = 4) readonly restrict buffer MatrixE { vec4 zeroPoint[]; };
layout(set = 0, binding = 5) writeonly buffer PartialBuffer { float P[]; };

shared float shared_sum;
shared vec4 xsCache[2][TS];
shared float sub_sums[TS / 64];

vec4 unpackInt4x4(uint packedComponent) {
    return vec4(uvec4(bitfieldExtract(packedComponent, 0, 4),
                      bitfieldExtract(packedComponent, 4, 4),
                      bitfieldExtract(packedComponent, 8, 4),
                      bitfieldExtract(packedComponent, 12, 4)));
}

vec4 unpackInt4x4High(uint packedComponent) {
    return vec4(uvec4(bitfieldExtract(packedComponent, 16, 4),
                      bitfieldExtract(packedComponent, 20, 4),
                      bitfieldExtract(packedComponent, 24, 4),
                      bitfieldExtract(packedComponent, 28, 4)));
}

void main() {
    uint col = gl_LocalInvocationID.x;
    uint chunk = gl_WorkGroupID.y;
    uint globalCol = gl_WorkGroupID.x*TS + col;
    uint safeCol = min(globalCol, param.N - 1u);

    uint scaleIdx = gl_WorkGroupID.x * param.K / vec;
    float sum_sq = 0.0;

    for (uint t = 0; t < param.K/vec; t+=TS) {
        vec4 val = x[t + col];
        sum_sq += dot(val, val);
    }

    sum_sq = subgroupAdd(sum_sq);
    if (subgroupElect()) {
        sub_sums[gl_SubgroupID] = sum_sq;
    }
    barrier();

    if (gl_LocalInvocationID.x == 0) {
        float final_sum = 0.0;
        uint active_subgroups = (TS + gl_SubgroupSize - 1) / gl_SubgroupSize;
        for (uint i = 0; i < active_subgroups; i++) {
            final_sum += sub_sums[i];
        }
        shared_sum = final_sum;
    }
    barrier();
    float inv_rms = 1.0 / sqrt((shared_sum / float(d_model)) + EPSILON);

    float ztot = 0.0;
    float acc = 0.0;
    uint numTiles = (param.K + TS - 1) / TS / vec;

    if (chunk < numTiles) {
        uint base = chunk*TS + col;
        vec4 xa = x[base] * gamma[base] * inv_rms;
        xsCache[0][col] = xa * scale[base + scaleIdx];
        float zp = subgroupAdd(dot(xa * zeroPoint[base + scaleIdx], vec4(1.0)));
        if (subgroupElect()) {
            sub_sums[gl_SubgroupID] = zp;
        }
    }
    barrier();
    if (chunk < numTiles) {
        ztot += sub_sums[0] + sub_sums[1] + sub_sums[2] + sub_sums[3];
    }

    uint it = 0;
    for (uint t = chunk; t < numTiles; t += 4u) {
        uint cur = it & 1, nxt = (it+1) & 1;
        uint nextTile = t + 4u;
        if (nextTile < numTiles) {
            uint base = nextTile*TS + col;
            vec4 xa = x[base] * gamma[base] * inv_rms;
            xsCache[nxt][col] = xa * scale[base + scaleIdx];
            float zp = subgroupAdd(dot(xa * zeroPoint[base + scaleIdx], vec4(1.0)));
            if (subgroupElect()) {
                sub_sums[gl_SubgroupID] = zp;
            }
        }
        barrier();
        if (nextTile < numTiles) {
            ztot += sub_sums[0] + sub_sums[1] + sub_sums[2] + sub_sums[3];
        }

        uint baseRow = t * (TS / 8) * param.N;
        #pragma unroll
        for (uint k=0;k<TS; k+=16) {
            uvec4 ra = w[baseRow + safeCol];
            uvec4 rb = w[baseRow + param.N + safeCol];
            acc += dot(xsCache[cur][k], unpackInt4x4(ra.x));
            acc += dot(xsCache[cur][k+1], unpackInt4x4High(ra.x));
            acc += dot(xsCache[cur][k+2], unpackInt4x4(ra.y));
            acc += dot(xsCache[cur][k+3], unpackInt4x4High(ra.y));
            acc += dot(xsCache[cur][k+4], unpackInt4x4(ra.z));
            acc += dot(xsCache[cur][k+5], unpackInt4x4High(ra.z));
            acc += dot(xsCache[cur][k+6], unpackInt4x4(ra.w));
            acc += dot(xsCache[cur][k+7], unpackInt4x4High(ra.w));
            acc += dot(xsCache[cur][k+8], unpackInt4x4(rb.x));
            acc += dot(xsCache[cur][k+9], unpackInt4x4High(rb.x));
            acc += dot(xsCache[cur][k+10], unpackInt4x4(rb.y));
            acc += dot(xsCache[cur][k+11], unpackInt4x4High(rb.y));
            acc += dot(xsCache[cur][k+12], unpackInt4x4(rb.z));
            acc += dot(xsCache[cur][k+13], unpackInt4x4High(rb.z));
            acc += dot(xsCache[cur][k+14], unpackInt4x4(rb.w));
            acc += dot(xsCache[cur][k+15], unpackInt4x4High(rb.w));
            baseRow += 2 * param.N;
        }

        barrier();
        it++;
    }

    if (globalCol < param.N) {
        P[chunk * param.N + globalCol] = acc - ztot;
    }
}
