#version 450
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#define TS 256
#define vec 4
#define d_model 4096

layout(local_size_x = TS, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Dimensions {
    uint M;
    uint N;
    uint K;
    uint off;
} dims;

const float EPSILON = 1e-6;

layout(set = 0, binding = 0) readonly restrict buffer MatrixA { vec4 x[]; };
layout(set = 0, binding = 1) readonly restrict buffer MatrixB { vec4 gamma[]; };
layout(set = 0, binding = 2) readonly restrict buffer MatrixC { uvec4 gate[]; };
layout(set = 0, binding = 3) readonly restrict buffer MatrixD { uvec4 up[]; };
layout(set = 0, binding = 4) writeonly restrict buffer PartialBuffer { float PgPu[]; };

shared float shared_sum;
shared vec4 cache[d_model/vec];
shared float sub_sums[TS / 64];

void main() {
    uint col = gl_LocalInvocationID.x;
    uint chunk = gl_WorkGroupID.y;
    uint globalCol = gl_WorkGroupID.x*TS + col;
    uint upHalf = uint(globalCol >= dims.off);
    if (upHalf == 1u) globalCol -= dims.off;

    float sum_sq = 0.0;
    for (uint t = 0; t < dims.K/vec; t+=TS) {
        uint idx = t + col;
        vec4 val = x[idx];
        cache[idx] = val * gamma[idx];
        sum_sq += dot(val, val);
    }

    sum_sq = subgroupAdd(sum_sq);
    if (subgroupElect()) {
        sub_sums[gl_SubgroupID] = sum_sq;
    }
    barrier();

    if (gl_LocalInvocationID.x == 0) {
        float final_sum = 0.0;
        uint active_subgroups = (TS + gl_SubgroupSize - 1) / gl_SubgroupSize;
        for (uint i = 0; i < active_subgroups; i++) {
            final_sum += sub_sums[i];
        }
        shared_sum = final_sum;
    }
    barrier();
    float rms = sqrt((shared_sum / float(d_model)) + EPSILON);
    float inv_rms = 1.0 / rms;

    uint kvStart = chunk * (dims.K / vec / 4u);
    uint kvEnd = kvStart + dims.K / vec / 4u;
    float result = 0.0;
    uint baseRow = (kvStart / 2) * dims.N;
    #pragma unroll
    for (uint k=kvStart;k<kvEnd; k+=2) {
        vec4 tempA0 = cache[k] * inv_rms;
        vec4 tempA1 = cache[k+1] * inv_rms;

        uvec4 rawInput;
        if (upHalf == 1u) rawInput = up[baseRow + globalCol];
        else rawInput = gate[baseRow + globalCol];
        vec4 outVectorA = vec4(unpackHalf2x16(rawInput.x), unpackHalf2x16(rawInput.y));
        vec4 outVectorB = vec4(unpackHalf2x16(rawInput.z), unpackHalf2x16(rawInput.w));
        result += dot(tempA0, outVectorA);
        result += dot(tempA1, outVectorB);
        baseRow += dims.N;
    }

    PgPu[(upHalf * 4u + chunk) * dims.N + globalCol] = result;
}
