#version 450
#extension GL_KHR_shader_subgroup_arithmetic : enable
#extension GL_KHR_shader_subgroup_basic : enable
#extension GL_EXT_shader_atomic_float : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_8bit_storage : require
#define TS 256
#define vec 4
#define d_model 4096
#define SPLIT 4

layout(local_size_x = TS, local_size_y = 1, local_size_z = 1) in;

layout(push_constant) uniform Dimensions {
    uint M;
    uint N;
    uint K;
} param;

const float EPSILON = 1e-5;

layout(set = 0, binding = 0) buffer DataBuffer { vec4 x[]; };
layout(set = 0, binding = 1) readonly buffer GammaBuffer { vec4 gamma[]; };
layout(set = 0, binding = 2) readonly buffer weightBuffer { uvec4 w[]; };
layout(set = 0, binding = 3) readonly restrict buffer MatrixD { vec4 scale[]; };
layout(set = 0, binding = 4) readonly restrict buffer MatrixE { vec4 zeroPoint[]; };
layout(set = 0, binding = 5) writeonly buffer PartialBuffer { float P[]; };

shared float shared_sum;
shared vec4 cache[d_model/vec];
shared vec4 scaleCache[d_model/vec];
shared vec4 zeroCache[d_model/vec];
shared float sub_sums[TS / 64];

vec4 unpackUint8x4(uint packedData) {
    uvec4 bytes = (uvec4(packedData) >> uvec4(0, 8, 16, 24)) & uvec4(0xFF);
    return vec4(bytes);
}

void main() {
    uint col = gl_LocalInvocationID.x;
    uint chunk = gl_WorkGroupID.y;
    uint globalCol = gl_WorkGroupID.x*TS + col;
    if (globalCol >= param.N) return;

    uint scaleIdx = gl_WorkGroupID.x * param.K / vec;
    float sum_sq = 0.0;

    for (uint t = 0; t < param.K/vec; t+=TS) {
        uint idx = t + col;
        vec4 val = x[idx];
        cache[idx] = val * gamma[idx];
        scaleCache[idx] = scale[idx + scaleIdx];
        zeroCache[idx] = zeroPoint[idx + scaleIdx];
        sum_sq += dot(val, val);
    }

    sum_sq = subgroupAdd(sum_sq);
    if (subgroupElect()) {
        sub_sums[gl_SubgroupID] = sum_sq;
    }
    barrier();

    if (gl_LocalInvocationID.x == 0) {
        float final_sum = 0.0;
        uint active_subgroups = (TS + gl_SubgroupSize - 1) / gl_SubgroupSize;
        for (uint i = 0; i < active_subgroups; i++) {
            final_sum += sub_sums[i];
        }
        shared_sum = final_sum;
    }
    barrier();
    float rms = sqrt((shared_sum / float(d_model)) + EPSILON);
    float inv_rms = 1.0 / rms;

    uint kvStart = chunk * (param.K / vec / SPLIT);
    uint kvEnd = kvStart + param.K / vec / SPLIT;
    float acc = 0.0;
    uint baseRow = (kvStart / 4) * param.N;
    #pragma unroll
    for (uint k=kvStart;k<kvEnd; k+=4) {
        uvec4 rawInput = w[baseRow + globalCol];
        vec4 w0 = unpackUint8x4(rawInput.x) * scaleCache[k] - zeroCache[k];
        vec4 w1 = unpackUint8x4(rawInput.y) * scaleCache[k+1] - zeroCache[k+1];
        vec4 w2 = unpackUint8x4(rawInput.z) * scaleCache[k+2] - zeroCache[k+2];
        vec4 w3 = unpackUint8x4(rawInput.w) * scaleCache[k+3] - zeroCache[k+3];
        acc += dot(cache[k] * inv_rms, w0);
        acc += dot(cache[k+1] * inv_rms, w1);
        acc += dot(cache[k+2] * inv_rms, w2);
        acc += dot(cache[k+3] * inv_rms, w3);
        baseRow += param.N;
    }

    P[chunk * param.N + globalCol] = acc;
}
